name:                lazy-option
version:             0.1.0.0
github:              "oisdk/lazy-option"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/oisdk/lazy-option#readme>

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
- -fwarn-redundant-constraints
- -Wcompat

tests:
  lazy-option-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazy-option
    - QuickCheck >= 1.0
    - checkers >= 0.1
    - ChasingBottoms >= 1.2.2
    - HUnit >=1.1
    - test-framework >=0.1
    - test-framework-quickcheck2 >=0.2.1
  lazy-option-doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - lazy-option
    - doctest
    - QuickCheck
